### ISSUE TITLE
Router refresh sometimes getting stuck in loops

### ISSUE THREAD

**Issue by nathanjhood** [StoneyDSP/stoneydsp.com#874]
# Bug report

I know this has been happening for the past few weeks but I've needed to take a break from the project in order to get some perspective and get back to some actual meaningful coding here.

Pretty sure I know why this is happening - async madness and a validation check that I haven't debugged enough (and don't really need anyway).

I'm gonna do a quick patch on this but leave the issue open to monitor - just in case I've got the wrong idea about what the cause is.

**Comment by nathanjhood** [comment]
So far so good...

**Comment by nathanjhood** [comment]
I've refactored the middleware, layout, and template to avoid some of the async/try/catch behaviour I was doing, this seems to have massively reduced the amount of incidents of the router getting stuck in loops.

I've still hit a loop incident while logging out and back in, and spotted some common patterns in the log around the times of these incidents occurring. I believe I have identified is a specific HTTP request/method that is capable of producing this issue.

Now that the issue is a bit more isolated from other possible causes, the information presently available suggests that a particular re-routing call is not being well-managed, and that it is possible to invoke a similar call manually using any HTTP request app/tool. 

My first point of investigation into this is suggests to be really careful about pre-fetching. I may need to create a safe "landing page" free of really any content, which can just be used in between routing, to ensure that those problematic re-routing requests can be sanitized before sending the user onwards to a page with lots of pre-fetched data.

I am not actually certain that a "middle" page for sanitation is a correct approach, and am considering raising the question in a discussion on the Next.Js repo.

**Comment by nathanjhood** [comment]
et viola... I think the last-mentioned rollback has bought the correct error-handling mechanism back into play. So now we are at least getting a sensible error message instead of getting stuck:

```.sh
 AuthApiError: Invalid Refresh Token: Refresh Token Not Found
    at (node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:40:10)
    at (node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:77:8)
    at (node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:62:17)
    at (node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:1291:23)
    at (node_modules/@supabase/gotrue-js/dist/module/lib/helpers.js:190:35) {
  __isAuthError: true,
  name: 'AuthApiError',
  status: 400
}
```

**Comment by nathanjhood** [comment]
```.sh
[GET] /?message=Invalid%20Refresh%20Token%3A%20Refresh%20Token%20Not%20Found status=200
```

**Comment by nathanjhood** [comment]
This hasn't happened lately and I think it may be related to NextJS going in circles while trying to pre-cache some resources from other external websites which point back to itself.

Since moving some resources around, things have improved.

Still monitoring, because I only made one small change out of a potential double dozen... so I can't be too sure either that the issue is fixed, nor that this was the solution.

**Comment by nathanjhood** [comment]
I think this is fixed... hasn't seemed to be an issue in a long time.

Will close now and re-open if the problem re-emerges.
